### ISSUE TITLE
send function return NULL

### ISSUE THREAD

**Issue by DamianKedzior** [Luwe/Kohana-Email#3]
Send function sends an e-mail and return NULL. In core.php is said that this function return integer with number of emails sent.
I use Swift-4.1.5. I would like to show message in case of e-mail was sent or not, but i don't know how because of this NULL value returned.

EDIT: I think I found a solution. You should change in core.php
self::$_mail->send($message);
to
return self::$_mail->send($message);

**Comment by Luwe** [comment]
Thanks for the notice. I'm quite busy, so I will change the function as soon as I have some free time.

**Comment by DamianKedzior** [comment]
No problem, thanks for the module.

**Comment by Luwe** [comment]
I've fixed this issue in this commit: 
https://github.com/Luwe/Kohana-Email/commit/ba3141c6ac79eeaee18b57505114d9149c22dfe0
